// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.5

package handler

import (
	"net/http"

	consumer "github.com/arizalsaputro/billing-engine/internal/handler/consumer"
	cron "github.com/arizalsaputro/billing-engine/internal/handler/cron"
	loans "github.com/arizalsaputro/billing-engine/internal/handler/loans"
	"github.com/arizalsaputro/billing-engine/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/billing/consume/check/delinquency",
				Handler: consumer.ConsumeCheckDelinquencyHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/billing/consume/delinquency",
				Handler: consumer.ConsumeDelinquencyHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/billing/consume/late",
				Handler: consumer.ConsumeLateFeeHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/billing/consume/pay",
				Handler: consumer.ConsumeRepaymentHandler(serverCtx),
			},
		},
		rest.WithPrefix("/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/billing/cron/delinquency",
				Handler: cron.ScheduleDelinquencyHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/billing/cron/late",
				Handler: cron.ScheduleLateFeeHandler(serverCtx),
			},
		},
		rest.WithPrefix("/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/billing/create",
				Handler: loans.CreateLoanHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/billing/delinquency/:loanId",
				Handler: loans.GetLoanDelinquencyHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/billing/outstanding/:loanId",
				Handler: loans.GetLoanOutstandingHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/billing/pay/:loanId",
				Handler: loans.CreateRepaymentHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/billing/pay/:paymentId",
				Handler: loans.GetRepaymentHandler(serverCtx),
			},
		},
		rest.WithPrefix("/v1"),
	)
}
